trigger:
  - develop

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
    displayName: "yarn install"

  - script: yarn run test
    displayName: "Run Jest tests"

  - script: eas upadate
    displayName: "Deploy to Expo"
