declare module "@env" {
  export const BASE_URL: string;
  export const API_BASE_URL: string;
  export const API_TOKEN: string;
  export const PORT: number;
  export const PWD: string;
  export const SENTRY_ORG: string;
  export const SENTRY_PROJECT: string;
  export const SENTRY_AUTH_TOKEN: string;
  export const ENV: string;
  export const GOOGLE_EXPO_CLINET_ID: string;
  export const GOOGLE_ANDROID_CLINET_ID: string;
  export const GOOGLE_IOS_CLINET_ID: string;
  export const FACEBOOK_IOS_CLINET_ID: string;
  export const FACEBOOK_ANDROID_CLINET_ID: string;
  export const FACEBOOK_EXPO_CLINET_ID: string;
  export const ACCESS_TOKEN_KEY: string;
  export const PREFERENCE_KEY: string;
}
